# -*- coding: utf-8 -*-
"""Axis Matplotlib plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWG25emk7cFhyLEA9T4zhVIYaTIrEny0
"""

import matplotlib.pyplot as plt
import numpy as np

x=[1,2,3,4,5]
y=[3,1,5,2,4]

plt.plot(x,y)

# plt.xticks(x)
# plt.yticks(y)
# plt.xlim(0,10)
# plt.ylim(0,10)

plt.axis([0,10,0,7])

plt.title("Graph")

plt.xlabel("x-axis")
plt.ylabel("y-axis")

plt.show()