# -*- coding: utf-8 -*-
"""Bar Chart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTLt15xwlIBtaw_1TP7LXhVQ4K9ElP1T
"""

import matplotlib.pyplot as plt

x=["python","C","C++","Java"]
y=[85,70,60,82]


plt.bar(x,y)
plt.show

x=["python","C","C++","Java"]
y=[85,70,60,82]
z=[95,65,55,70]

plt.xlabel("language" , fontsize=20)
plt.ylabel("Popularity",fontsize=20)
plt.title("bar chart",fontsize=20)
c=["y","b","g","m"]
# plt.bar(x,y, width=0.4,color=c,align="edge",edgecolor="r",linewidth=5,linestyle=":",alpha=0.8,)
plt.bar(x,y, width=0.4,color="r",label="Bar Chart")
plt.bar(x,z, width=0.4,color="g",label="Bar Chart")
plt.legend()
plt.show

import numpy as np
x=["python","C","C++","Java"]
y=[85,70,60,82]
z=[65,35,25,50]
width=0.2
p=np.arange(len(x))
p1=[j+width for j in p]

plt.xlabel("language" , fontsize=20)
plt.ylabel("Popularity",fontsize=20)
plt.title("bar chart",fontsize=20)

plt.bar(p,y,width,color="r",label="Bar Chart")
plt.bar(p1,z,width,color="g",label="Bar Chart")

plt.xticks(p+width/2,x,rotation=30)
plt.legend()
plt.show