# -*- coding: utf-8 -*-
"""box plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWG25emk7cFhyLEA9T4zhVIYaTIrEny0
"""

import matplotlib.pyplot as plt

x=[10,20,30,40,50,60,70]
x1=[90,80,70,60,50,40,30]
y=[x,x1]
# plt.boxplot(x,notch=True,)
# plt.boxplot(x,widths=0.4)

# plt.boxplot(x,labels=["Box Plot"])
# plt.boxplot(x,patch_artist=True)
# plt.boxplot(x,showmeans=True,whis=1.5 , sym="g+", boxprops=dict(color="r"),capprops=dict(color="r"), whiskerprops=dict(color="r")
# ,medianprops=dict(color="r"),flierprops=dict(color="r"))
# plt.boxplot(x)
# plt.legend()
plt.boxplot(y)
plt.show()