# -*- coding: utf-8 -*-
"""Fill between plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWG25emk7cFhyLEA9T4zhVIYaTIrEny0
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,3,4,5])
y=np.array([1,2,3,4,5])

plt.plot(x,y,color='black')
plt.fill_between(x,y,where=(x>=2)&(x<=4),alpha=0.5)
# plt.fill_between(x=[2,4],y1=2,y2=4)
plt.title('Fill Between')
plt.xlabel('x')
plt.ylabel('y')
plt.grid(True)
plt.show()