# -*- coding: utf-8 -*-
"""First Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTLt15xwlIBtaw_1TP7LXhVQ4K9ElP1T
"""

import matplotlib.pyplot as plt

x=[1,2,3,4]
y=[2,4,6,8]

c=["r",'y',"g",'b']
plt.bar(x,y,color=c)
print(plt.show)