# -*- coding: utf-8 -*-
"""Histogram Plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTLt15xwlIBtaw_1TP7LXhVQ4K9ElP1T
"""

import matplotlib.pyplot as plt
import numpy as np
import random

x=np.random.randint(10,60,(50))
x

no=[39, 49, 45, 32, 40, 11, 51, 53, 51, 32, 24, 11, 37, 18, 48, 53, 55,
       46, 29, 14, 37, 22, 26, 39, 43, 43, 28, 40, 21, 29, 14, 28, 31, 26,
       55, 30, 13, 12, 30, 40, 56, 57, 57, 18, 35, 55, 10, 36, 23, 56]

# l=[10,20,30,40,50,60]
# bins=l
# plt.hist(no,"auto",(0,100),edgecolor='r')
# plt.hist(no,edgecolor='r',cumulative=-1)
# plt.hist(no,edgecolor='r',bottom=10)
# plt.hist(no,edgecolor='r',align="left")
# plt.hist(no,edgecolor='r',histtype="step")
# plt.hist(no,edgecolor='r',orientation="horizontal")
# plt.hist(no,edgecolor='r',rwidth=0.9)
# plt.hist(no,edgecolor='r',log=True)
plt.hist(no,edgecolor='r',label="Python")

plt.title("Histogram")
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.axvline(40,color='black',label="Average")
plt.grid()
plt.legend()

plt.show()