# -*- coding: utf-8 -*-
"""Pie Chart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWG25emk7cFhyLEA9T4zhVIYaTIrEny0
"""

import matplotlib.pyplot as plt

x=[10,20,30,40]
x1=[40,30,20,10]
y=["c","c++","java","python"]
# ex=[0.2,0.0,0.0,0.0]

# plt.pie(x,labels=y,explode=ex,autopct="%0.1f%%",shadow=True,radius=0.9,labeldistance=1.1,startangle=180)
# plt.pie(x,labels=y,explode=ex,autopct="%0.1f%%",shadow=True)
# plt.pie(x,labels=y,explode=ex,autopct="%0.1f%%",radius=0.9)
# plt.pie(x,labels=y,explode=ex,autopct="%0.1f%%",labeldistance=1.1)
# plt.pie(x,labels=y,explode=ex,autopct="%0.1f%%",startangle=180)
# plt.pie(x,labels=y,explode=ex,autopct="%0.1f%%",textprops={"fontsize":15})
# plt.pie(x,labels=y,autopct="%0.1f%%",counterclock=False)
# plt.pie(x,labels=y,autopct="%0.1f%%",wedgeprops={"linewidth":2,"edgecolor":"black"})
# plt.pie(x,labels=y,autopct="%0.1f%%",center=(3,3))
# plt.pie(x,labels=y,autopct="%0.1f%%",rotatelabels=True)

plt.pie(x,labels=y,radius=1)
plt.pie(x1,radius=0.5)



plt.title("pie chart")
# plt.legend(loc=2)
plt.show()

x=[10,20,30,40]
x1=[40,30,20,10]
y=["c","c++","java","python"]

plt.pie(x,labels=y,radius=1)
cr=plt.Circle(xy=(0,0),radius=0.7,facecolor="w")
plt.gca().add_artist(cr)
# plt.pie(x1,radius=0.5)



plt.title("pie chart")
# plt.legend(loc=2)
plt.show()