# -*- coding: utf-8 -*-
"""Savefig plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWG25emk7cFhyLEA9T4zhVIYaTIrEny0
"""

import matplotlib.pyplot as plt
import numpy as np

x=[1,2,3,4,5]
y=[2,4,3,6,1]

plt.plot(x,y)
# plt.savefig('Savefig.pdf',dpi=2000,facecolor="Black",box_inches="tight")
# plt.show()