# -*- coding: utf-8 -*-
"""Scatter Plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTLt15xwlIBtaw_1TP7LXhVQ4K9ElP1T
"""

import matplotlib.pyplot as plt

day=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
no=[2,4,6,5,7,9,1]
no1=[9,7,5,3,1,2,4]
no2=[1,3,3,7,9,8,6]

color=[10,20,30,40,50,60,70]
# plt.scatter(day,no,c=color,marker="*",cmap="viridis")
plt.scatter(day,no,color='b',marker="*")
plt.scatter(day,no1,color='g',marker="*")
plt.scatter(day,no2,color='r',marker="*")

# t=plt.colorbar()
# t.set_label("colorbar")
# Color Maps

plt.title('Scatter Plot',fontsize=20)
plt.xlabel('Day',fontsize=15)
plt.ylabel('No.',fontsize=15)
plt.show

