# -*- coding: utf-8 -*-
"""Stack plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWG25emk7cFhyLEA9T4zhVIYaTIrEny0
"""

import matplotlib.pyplot as plt

x=[1,2,3,4,5,6]
area=[2,4,5,6,3,7]
area1=[5,3,6,3,6,7]
area2=[4,2,5,6,3,1]
l=["area","area1","area2"]
# plt.stackplot(x,area,area1,area2,labels=l,baseline="wiggle,sym")
plt.stackplot(x,area,area1,area2,labels=l)

plt.legend()
plt.show()