# -*- coding: utf-8 -*-
"""Stem plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWG25emk7cFhyLEA9T4zhVIYaTIrEny0
"""

import matplotlib.pyplot as plt

x=[1,2,3,4,5,6]
y=[2,2,5,7,8,3]

# plt.stem(x,y,linefmt=":",markerfmt="r+",bottom=2,basefmt="g",label="python")

plt.stem(x,y)
plt.legend()
plt.show()

