# -*- coding: utf-8 -*-
"""Step plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWG25emk7cFhyLEA9T4zhVIYaTIrEny0
"""

import matplotlib.pyplot as plt

x=[1,2,3,4,5]
y=[1,2,3,4,5]

plt.step(x,y,marker='o',color='r')
plt.xlabel('x')
plt.ylabel('y')
plt.title('step')
plt.grid()
plt.show()