# -*- coding: utf-8 -*-
"""Text in Matplotlib plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWG25emk7cFhyLEA9T4zhVIYaTIrEny0
"""

import matplotlib.pyplot as plt
import numpy as np

x=[1,2,3,4,5]
y=[3,1,5,2,4]

plt.plot(x,y)
plt.title('Line Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.text(2,4,"Profit")
plt.text(1,4,"lose",bbox={"facecolor":"red"})

plt.annotate("Python",xy=(2,1),xytext=(2.5,1.5),arrowprops=dict(facecolor="black",shrink=100))
plt.show()